
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri May 31 11:56:12 EDT 2019
//----------------------------------------------------

package mjparser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GIVENS = 2;
  public static final int DELTA_VARIABLE = 6;
  public static final int GTEQ = 11;
  public static final int NUMBER = 7;
  public static final int RAWTYPE = 4;
  public static final int SEMI = 12;
  public static final int VARIABLE = 5;
  public static final int EOF = 0;
  public static final int GT = 10;
  public static final int EVENTS = 3;
  public static final int COMMA = 13;
  public static final int error = 1;
  public static final int COMMENT = 14;
  public static final int LTEQ = 9;
  public static final int LT = 8;
}

