
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jun 05 15:49:03 EDT 2019
//----------------------------------------------------

package mjparser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DELTA_VARIABLE = 6;
  public static final int LT = 13;
  public static final int EVENTS = 3;
  public static final int NOTEQ = 12;
  public static final int SEMI = 17;
  public static final int RAWTYPE = 4;
  public static final int VARIABLE = 5;
  public static final int GT = 15;
  public static final int DELTA = 8;
  public static final int COMMA = 18;
  public static final int LTEQ = 14;
  public static final int EOF = 0;
  public static final int NUMBER = 10;
  public static final int DEF = 9;
  public static final int COMMENT = 19;
  public static final int error = 1;
  public static final int EQ = 11;
  public static final int GTEQ = 16;
  public static final int GIVENS = 2;
  public static final int THRESHOLD = 7;
}

