package inference_engine;

public enum RawType{

   STRING, INT, DOUBLE, BOOLEAN, EXPRESSION, INTEXP, DOUBLEEXP, STRINGEXP, INTDELTA, DOUBLEDELTA, STRINGDELTA, CONSTRAINT
   //TODO: add STRINGDELTA
}
