
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Aug 07 17:30:08 EDT 2019
//----------------------------------------------------

package mjparser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DELTA_VARIABLE = 11;
  public static final int LT = 18;
  public static final int GIVEN = 7;
  public static final int NOTEQ = 17;
  public static final int EVENTS = 3;
  public static final int RPAREN = 8;
  public static final int SEMI = 24;
  public static final int RAWTYPE = 5;
  public static final int P_LPAREN = 6;
  public static final int VARIABLE = 10;
  public static final int LOGICAL_AND = 22;
  public static final int GT = 20;
  public static final int STRING_TRANSITION = 27;
  public static final int CONSTRAINTS = 4;
  public static final int DELTA = 13;
  public static final int STRING = 9;
  public static final int COMMA = 25;
  public static final int LTEQ = 19;
  public static final int EOF = 0;
  public static final int NUMBER = 15;
  public static final int DEF = 14;
  public static final int COMMENT = 26;
  public static final int error = 1;
  public static final int EQ = 16;
  public static final int GTEQ = 21;
  public static final int GIVENS = 2;
  public static final int THRESHOLD = 12;
  public static final int LOGICAL_OR = 23;
}

